### ISSUE TITLE
Change paths from array to dot notation

### ISSUE THREAD

**Issue by jjwilliams42** [nervgh/object-to-formdata#3]
Thanks for this, it's almost exactly what I needed. The only issue I have is my server expects a format of:

Entity.SomeArray[0].SomeProperty

but this plugin uses the array notation

Entity[SomeArray][0][SomeProperty]

The module is so simple and elegant, yet I am having a hard time wrapping my head around how to make the modifications. Can you shed any light or point me in the right direction?

**Comment by nervgh** [comment]
You are welcome.
It looks like I forgot to mark this "package" as deprecated =)
Please, follow to next [link](https://github.com/nervgh/recursive-iterator/wiki/Cookbook-%28es6%29#to-form-data).
